[development]

[testing]

[prodtemp]

[production]
SERVER = '170.238.84.12'
DATABASE = 'WGC'
USERNAME = 'wgcplayip'
PASSWORD = 'teste01*'
USEDOCKER = true
TEST = 0
MONGO_DB_HOST="mongo"
MONGO_DB_PORT=27017
