[development]

[testing]

[prodtemp]

[production]
SERVER = '170.238.84.126'
DATABASE = 'WGC'
USERNAME = 'wgcplayip'
PASSWORD = 'teste01*'
USEDOCKER = true
TEST = 0
MONGO_DB_HOST="mongo"
MONGO_DB_PORT=27017
NO_OAUTH = 0
PLAYIPAPP_URL = "http://apphub:8008"
